# Kelvin release configuration
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0

    targets:
      - linux_arm_5

archives:
  - format_overrides:
      - goos: windows
        format: zip
    
    files:
      - LICENSE
      - README.md
      - gui/*
      - etc/*

    rlcp: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
